import { useEffect, useRef, useState } from 'react'
import { Upload, FileText, Lock, CheckCircle2, ShieldAlert, Eye, Loader2 } from 'lucide-react'
import { Button } from '../ui/Button'
import { StatusChip } from '../ui/StatusChip'
import { Field, Select, TextInput, Textarea } from '../ui/Field'
import { BookingMilestonesSection } from './BookingMilestonesSection'
import { useDataStore } from '../../store/useDataStore'
import { useAuthStore, useCurrentUser } from '../../store/useAuthStore'
import type { BlFields, Booking, DocType, MilestoneDef, MilestoneEntry } from '../../lib/types'

/* Doc §5 — the 12-document sequence, in display order */
export const DOC_SEQUENCE: { type: DocType; trigger: string }[] = [
  { type: 'CRO', trigger: 'Generated by MNR after booking saved' },
  { type: 'VGM', trigger: 'Filed before cut-off; auto-linked to container activity' },
  { type: 'CLP', trigger: 'Submitted at gate-in / stuffing confirmation' },
  { type: 'Shipping Bill', trigger: 'Filed with customs before vessel departure' },
  { type: 'BL', trigger: 'Created in BL panel; released after vessel sails' },
  { type: 'SOB', trigger: 'Confirmed when vessel departs; notation on BL' },
  { type: 'Offloading Letter', trigger: 'If required — uploaded to docs tab' },
  { type: 'DO', trigger: 'Import only — issued after cargo arrival and payment' },
  { type: 'CAN', trigger: 'Import only — sent to consignee on vessel arrival' },
  { type: 'Commercial Invoice + Packing List', trigger: 'Customer uploads for customs compliance' },
  { type: 'Certificate of Origin', trigger: 'Customer uploads where required' },
  { type: 'MSDS', trigger: 'Required for hazardous cargo (see Product info)' },
  { type: 'Non-Haz Declaration', trigger: 'Required to declare cargo as non-hazardous' },
]

export type BlFieldWidget = 'text' | 'textarea' | 'select'

export const BL_FIELD_LABELS: { key: keyof BlFields; label: string; widget: BlFieldWidget; options?: string[] }[] = [
  { key: 'shipper', label: 'Shipper', widget: 'textarea' },
  { key: 'consignee', label: 'Consignee', widget: 'textarea' },
  { key: 'notifyParty', label: 'Notify Party', widget: 'textarea' },
  { key: 'overseasAgent', label: 'Overseas Agent', widget: 'textarea' },
  { key: 'vessel', label: 'Vessel', widget: 'text' },
  { key: 'voyage', label: 'Voyage', widget: 'text' },
  { key: 'placeOfReceipt', label: 'Place of Receipt', widget: 'text' },
  { key: 'portOfLoading', label: 'Port of Loading', widget: 'text' },
  { key: 'placeOfDischarge', label: 'Place of Discharge', widget: 'text' },
  { key: 'finalPlaceOfDelivery', label: 'Final Place of Delivery', widget: 'text' },
  { key: 'blDate', label: 'BL Date', widget: 'text' },
  { key: 'shippedOnBoard', label: 'Shipped On Board', widget: 'text' },
  { key: 'placeOfIssue', label: 'Place of Issue', widget: 'text' },
  { key: 'numberOfOriginals', label: 'Number of Originals', widget: 'text' },
  { key: 'blNumber', label: 'Bill of Lading Number', widget: 'text' },
  { key: 'blNumberManual', label: 'Bill of Lading Number (MANUAL)', widget: 'text' },
  { key: 'movementType', label: 'Movement Type', widget: 'text' },
  { key: 'blType', label: 'BL Type', widget: 'text' },
  { key: 'shipmentReference', label: 'Shipment Reference', widget: 'text' },
  { key: 'containers', label: 'Containers', widget: 'textarea' },
  { key: 'packagesAndDescription', label: 'Number and Kind of Packages, Description of Goods', widget: 'textarea' },
  { key: 'weight', label: 'Weight', widget: 'textarea' },
  { key: 'measurement', label: 'Measurement', widget: 'textarea' },
  { key: 'otherParticulars', label: 'Other Particulars', widget: 'textarea' },
  { key: 'freight', label: 'Freight', widget: 'text' },
  { key: 'freightPayableAt', label: 'Freight Payable at', widget: 'text' },
  { key: 'collectCharges', label: 'Collect Charges', widget: 'text' },
  { key: 'releaseType', label: 'Release Type', widget: 'select', options: ['', 'Original', 'Telex', 'Seaway'] },
  { key: 'annexure', label: 'Annexure', widget: 'textarea' },
  { key: 'signingAgent', label: 'Signing Agent', widget: 'text' },
  { key: 'lockBlForClient', label: 'Lock BL For Client', widget: 'select', options: ['0', '1'] },
  { key: 'destinationAgentAccess', label: 'Destination Agent Access', widget: 'text' },
  { key: 'transhipmentAgentAccess', label: 'Transhipment Agent Access', widget: 'text' },
]

export function DocumentsTab({
  booking,
  milestones,
}: {
  booking: Booking
  milestones?: {
    defs: MilestoneDef[]
    entries: MilestoneEntry[]
    onMark: (key: string, completedAt: string) => void
    onEditDate: (key: string, completedAt: string) => void
  }
}) {
  const {
    documents,
    blStates,
    blVersions,
    saveBl,
    submitCustomerBlEdit,
    approveBl,
    releaseBl,
    fetchDocuments,
    uploadDocumentFile,
    getDocumentUrl,
  } = useDataStore()
  const currentUser = useCurrentUser()
  const viewAsRole = useAuthStore((s) => s.viewAsRole)
  const effectiveRole = viewAsRole ?? currentUser?.role
  const isAdmin = effectiveRole === 'admin'

  useEffect(() => {
    fetchDocuments(booking.id)
  }, [fetchDocuments, booking.id])

  const docs = documents.filter((d) => d.bookingId === booking.id)
  const bl = blStates.find((b) => b.bookingId === booking.id)
  const versions = blVersions.filter((v) => v.bookingId === booking.id)

  const [editing, setEditing] = useState(false)
  const [draft, setDraft] = useState<BlFields | null>(null)

  const startEdit = () => {
    setDraft(
      bl?.currentFields ?? {
        shipper: booking.shipper,
        consignee: booking.consignee,
        notifyParty: booking.notifyParty,
        overseasAgent: '',
        vessel: booking.vesselName,
        voyage: booking.voyageNo,
        placeOfReceipt: booking.pol,
        portOfLoading: booking.pol,
        placeOfDischarge: booking.pod,
        finalPlaceOfDelivery: booking.pod,
        blDate: '',
        shippedOnBoard: '',
        placeOfIssue: '',
        numberOfOriginals: '',
        blNumber: booking.hblNo ?? '',
        blNumberManual: '',
        movementType: '',
        blType: '',
        shipmentReference: '',
        containers: booking.containerNos.join(', '),
        packagesAndDescription: booking.commodity,
        weight: booking.grossWeightKg ? `GROSS WEIGHT\n${booking.grossWeightKg.toLocaleString()} KGS` : '',
        measurement: '',
        otherParticulars: '',
        freight: booking.freightTerms.toUpperCase(),
        freightPayableAt: '',
        collectCharges: '',
        releaseType: '',
        annexure: '',
        signingAgent: '',
        lockBlForClient: '0',
        destinationAgentAccess: '',
        transhipmentAgentAccess: '',
      },
    )
    setEditing(true)
  }

  const locked = bl?.lifecycle === 'Approved' || bl?.lifecycle === 'Released'

  return (
    <div className="space-y-6">
      {/* ── BL panel (doc §4) ── */}
      <div className="rounded-card border border-line bg-surface-2/40 p-5">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <FileText size={17} className="text-primary" />
            <h3 className="text-[15px] font-semibold">BL panel</h3>
            {bl && (
              <span className="rounded-badge bg-surface-2 px-2.5 py-1 text-xs font-medium text-heading">
                {bl.lifecycle}
                {bl.releaseType ? ` — ${bl.releaseType}` : ''}
              </span>
            )}
            {locked && <Lock size={13} className="text-muted" />}
          </div>
          <div className="flex flex-wrap gap-2">
            {!editing && !locked && (
              <Button size="sm" variant="secondary" onClick={startEdit}>
                {bl ? 'Edit BL draft' : 'Create BL draft'}
              </Button>
            )}
            {bl && !locked && bl.lifecycle !== 'Awaiting approval' && (
              isAdmin ? (
                <Button size="sm" onClick={() => approveBl(booking.id, currentUser?.name ?? 'Admin')}>
                  Approve & lock
                </Button>
              ) : (
                <span className="flex items-center gap-1.5 rounded-badge bg-[#FEF3C7] px-2.5 py-1 text-xs font-medium text-[#B45309]">
                  <ShieldAlert size={13} /> Awaiting Admin approval
                </span>
              )
            )}
            {bl?.lifecycle === 'Approved' && (
              <>
                {(['Original', 'Telex', 'Seaway'] as const).map((t) => (
                  <Button key={t} size="sm" variant="secondary" onClick={() => releaseBl(booking.id, t)}>
                    Release {t}
                  </Button>
                ))}
              </>
            )}
            {locked && !editing && (
              <Button size="sm" variant="ghost" onClick={startEdit}>
                Amendment (revision cycle)
              </Button>
            )}
          </div>
        </div>

        <p className="mt-1.5 text-xs text-muted">
          Lifecycle: Draft → Agent/customer edited → Awaiting ops approval → Approved (locked) → Released
          (Original / Telex / Seaway).
        </p>

        {editing && draft ? (
          <div className="mt-4">
            <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
              {BL_FIELD_LABELS.map(({ key, label, widget, options }) => (
                <Field key={key} label={label}>
                  {widget === 'textarea' ? (
                    <Textarea
                      value={draft[key]}
                      onChange={(e) => setDraft((d) => (d ? { ...d, [key]: e.target.value } : d))}
                    />
                  ) : widget === 'select' ? (
                    <Select
                      value={draft[key]}
                      onChange={(e) => setDraft((d) => (d ? { ...d, [key]: e.target.value } : d))}
                    >
                      {options!.map((o) => (
                        <option key={o} value={o}>{o || '—'}</option>
                      ))}
                    </Select>
                  ) : (
                    <TextInput
                      value={draft[key]}
                      onChange={(e) => setDraft((d) => (d ? { ...d, [key]: e.target.value } : d))}
                    />
                  )}
                </Field>
              ))}
            </div>
            <div className="mt-4 flex flex-wrap gap-2">
              <Button
                size="sm"
                onClick={() => {
                  saveBl(booking.id, draft, 'S. Singh', 'ops')
                  setEditing(false)
                }}
              >
                Save — Ops (direct, versioned)
              </Button>
              <Button
                size="sm"
                variant="secondary"
                onClick={() => {
                  saveBl(booking.id, draft, 'Destination agent', 'agent')
                  setEditing(false)
                }}
              >
                Save — Agent (live, versioned)
              </Button>
              <Button
                size="sm"
                variant="secondary"
                onClick={() => {
                  const changes: Partial<BlFields> = {}
                  const baseline = bl?.currentFields
                  for (const { key } of BL_FIELD_LABELS) {
                    if (!baseline || baseline[key] !== draft[key]) changes[key] = draft[key]
                  }
                  submitCustomerBlEdit(booking.id, changes, booking.bookingPartyName)
                  setEditing(false)
                }}
              >
                Submit — Customer (approval-gated)
              </Button>
              <Button size="sm" variant="ghost" onClick={() => setEditing(false)}>
                Cancel
              </Button>
            </div>
          </div>
        ) : bl ? (
          <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">
            {BL_FIELD_LABELS.map(({ key, label }) => (
              <div key={key} className="rounded-btn border border-line bg-surface px-3 py-2">
                <p className="font-mono text-[10px] uppercase tracking-wide text-muted">{label}</p>
                <p className="mt-0.5 whitespace-pre-line text-[13px] text-heading">{bl.currentFields[key] || '—'}</p>
              </div>
            ))}
          </div>
        ) : (
          <p className="mt-4 text-sm text-muted">No BL draft yet — create one after container pickup.</p>
        )}

        {versions.length > 0 && (
          <div className="mt-5 border-t border-line pt-4">
            <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted">
              Version history (bl_versions — append-only)
            </p>
            <div className="space-y-1.5">
              {versions
                .slice()
                .reverse()
                .map((v) => (
                  <div key={v.id} className="flex items-center gap-3 text-xs text-body">
                    <span className="font-mono font-semibold text-heading">v{v.version}</span>
                    <span>{v.editedBy} ({v.editedByRole})</span>
                    <span className="text-muted">{new Date(v.editedAt).toLocaleString()}</span>
                    {v.amendment && (
                      <span className="rounded-badge bg-[#FEF3C7] px-2 py-0.5 text-[10px] font-semibold text-[#B45309]">
                        amendment
                      </span>
                    )}
                  </div>
                ))}
            </div>
          </div>
        )}
      </div>

      {milestones && (
        <BookingMilestonesSection
          title="Booking milestones"
          defs={milestones.defs}
          entries={milestones.entries}
          onMark={milestones.onMark}
          onEditDate={milestones.onEditDate}
        />
      )}

      {/* ── Documents sequence (doc §5) ── */}
      <div>
        <p className="mb-3 text-xs font-semibold uppercase tracking-wide text-muted">
          Documents — sequence and trigger
        </p>
        {!booking.dbId && (
          <p className="mb-3 rounded-btn border border-line bg-surface-2 px-3 py-2 text-xs text-muted">
            This is demo data, not a saved booking — real file upload is unavailable here. Create a new booking to try it.
          </p>
        )}
        <div className="space-y-2">
          {DOC_SEQUENCE.map((d, i) => {
            const uploaded = docs.find((x) => x.docType === d.type)
            return (
              <DocumentRow
                key={d.type}
                index={i}
                docType={d.type}
                trigger={d.trigger}
                uploaded={uploaded}
                canUpload={!!booking.dbId}
                onUpload={(file) => uploadDocumentFile(booking.id, d.type, currentUser?.name ?? 'Ops', file)}
                onView={uploaded?.storagePath ? () => getDocumentUrl(uploaded.storagePath!) : undefined}
              />
            )
          })}
        </div>
      </div>
    </div>
  )
}

export function DocumentRow({
  index,
  docType,
  trigger,
  uploaded,
  canUpload,
  onUpload,
  onView,
}: {
  index: number
  docType: DocType
  trigger: string
  uploaded: { status: string; uploadedBy: string | null; storagePath?: string } | undefined
  canUpload: boolean
  onUpload: (file: File) => Promise<{ error: string | null }>
  onView?: () => Promise<string | null>
}) {
  const fileInputRef = useRef<HTMLInputElement>(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')

  const pickFile = () => {
    setError('')
    fileInputRef.current?.click()
  }

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    e.target.value = '' // allow re-selecting the same file later
    if (!file) return
    setBusy(true)
    setError('')
    const { error: uploadError } = await onUpload(file)
    setBusy(false)
    if (uploadError) setError(uploadError)
  }

  const handleView = async () => {
    if (!onView) return
    const url = await onView()
    if (url) window.open(url, '_blank', 'noopener,noreferrer')
    else setError('Could not open document — try again.')
  }

  return (
    <div className="rounded-btn border border-line bg-surface px-4 py-2.5">
      <div className="flex items-center gap-3">
        <span className="w-6 font-mono text-[11px] text-muted">{String(index + 1).padStart(2, '0')}</span>
        <div className="flex-1 min-w-0">
          <p className="text-[13px] font-medium text-heading">{docType}</p>
          <p className="truncate text-[11px] text-muted">{trigger}</p>
        </div>
        {uploaded ? (
          <div className="flex items-center gap-2">
            <span className="flex items-center gap-1.5 text-xs text-primary">
              <CheckCircle2 size={14} />
              {uploaded.status} · {uploaded.uploadedBy}
            </span>
            {onView && (
              <Button size="sm" variant="ghost" onClick={handleView}>
                <Eye size={13} /> View
              </Button>
            )}
          </div>
        ) : (
          <>
            <StatusChip status="Pending" />
            <input ref={fileInputRef} type="file" hidden onChange={handleFileChange} />
            <Button size="sm" variant="ghost" disabled={!canUpload || busy} onClick={pickFile} className="disabled:opacity-40">
              {busy ? <Loader2 size={13} className="animate-spin" /> : <Upload size={13} />}
              {busy ? 'Uploading…' : 'Upload'}
            </Button>
          </>
        )}
      </div>
      {error && <p className="mt-1.5 ml-9 text-[11px] text-accent-coral">{error}</p>}
    </div>
  )
}
