import { useState } from 'react'
import { Upload, FileText, Lock, CheckCircle2 } from 'lucide-react'
import { Button } from '../ui/Button'
import { StatusChip } from '../ui/StatusChip'
import { Field, TextInput } from '../ui/Field'
import { useDataStore } from '../../store/useDataStore'
import type { BlFields, Booking, DocType } from '../../lib/types'

/* Doc §5 — the 12-document sequence, in display order */
const DOC_SEQUENCE: { type: DocType; trigger: string }[] = [
  { type: 'CRO', trigger: 'Generated by MNR after booking saved' },
  { type: 'SI', trigger: 'Customer uploads / ops enters before SI cut-off' },
  { type: 'VGM', trigger: 'Filed before cut-off; auto-linked to container activity' },
  { type: 'CLP', trigger: 'Submitted at gate-in / stuffing confirmation' },
  { type: 'Shipping Bill', trigger: 'Filed with customs before vessel departure' },
  { type: 'BL', trigger: 'Created in BL panel; released after vessel sails' },
  { type: 'SOB', trigger: 'Confirmed when vessel departs; notation on BL' },
  { type: 'Offloading Letter', trigger: 'If required — uploaded to docs tab' },
  { type: 'DO', trigger: 'Import only — issued after cargo arrival and payment' },
  { type: 'CAN', trigger: 'Import only — sent to consignee on vessel arrival' },
  { type: 'Commercial Invoice + Packing List', trigger: 'Customer uploads for customs compliance' },
  { type: 'Certificate of Origin', trigger: 'Customer uploads where required' },
]

const BL_FIELD_LABELS: { key: keyof BlFields; label: string; source: string }[] = [
  { key: 'shipper', label: 'Shipper', source: 'Auto from booking' },
  { key: 'consignee', label: 'Consignee', source: 'Auto from booking' },
  { key: 'notifyParty', label: 'Notify party', source: 'Auto from booking' },
  { key: 'pol', label: 'Port of loading', source: 'Auto from booking' },
  { key: 'pod', label: 'Port of discharge', source: 'Auto from booking' },
  { key: 'vesselVoyage', label: 'Vessel + voyage', source: 'Auto from booking' },
  { key: 'descriptionOfGoods', label: 'Description of goods', source: 'Ops enters' },
  { key: 'grossWeight', label: 'Gross weight', source: 'From VGM' },
  { key: 'marksAndNumbers', label: 'Marks and numbers', source: 'Ops enters' },
  { key: 'packages', label: 'Number of packages', source: 'Ops enters' },
]

export function DocumentsTab({ booking }: { booking: Booking }) {
  const { documents, blStates, blVersions, uploadDocument, saveBl, submitCustomerBlEdit, approveBl, releaseBl } =
    useDataStore()

  const docs = documents.filter((d) => d.bookingId === booking.id)
  const bl = blStates.find((b) => b.bookingId === booking.id)
  const versions = blVersions.filter((v) => v.bookingId === booking.id)

  const [editing, setEditing] = useState(false)
  const [draft, setDraft] = useState<BlFields | null>(null)

  const startEdit = () => {
    setDraft(
      bl?.currentFields ?? {
        shipper: booking.shipper,
        consignee: booking.consignee,
        notifyParty: booking.notifyParty,
        pol: booking.pol,
        pod: booking.pod,
        vesselVoyage: `${booking.vesselName} / ${booking.voyageNo}`,
        descriptionOfGoods: '',
        grossWeight: booking.grossWeightKg ? `${booking.grossWeightKg.toLocaleString()} kg` : '',
        marksAndNumbers: '',
        packages: booking.packages ? `${booking.packages} ${booking.packageType.toLowerCase()}` : '',
      },
    )
    setEditing(true)
  }

  const locked = bl?.lifecycle === 'Approved' || bl?.lifecycle === 'Released'

  return (
    <div className="space-y-6">
      {/* ── BL panel (doc §4) ── */}
      <div className="rounded-card border border-line bg-surface-2/40 p-5">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <FileText size={17} className="text-primary" />
            <h3 className="text-[15px] font-semibold">BL panel</h3>
            {bl && (
              <span className="rounded-badge bg-surface-2 px-2.5 py-1 text-xs font-medium text-heading">
                {bl.lifecycle}
                {bl.releaseType ? ` — ${bl.releaseType}` : ''}
              </span>
            )}
            {locked && <Lock size={13} className="text-muted" />}
          </div>
          <div className="flex flex-wrap gap-2">
            {!editing && !locked && (
              <Button size="sm" variant="secondary" onClick={startEdit}>
                {bl ? 'Edit BL draft' : 'Create BL draft'}
              </Button>
            )}
            {bl && !locked && bl.lifecycle !== 'Awaiting approval' && (
              <Button size="sm" onClick={() => approveBl(booking.id)}>
                Approve & lock
              </Button>
            )}
            {bl?.lifecycle === 'Approved' && (
              <>
                {(['Original', 'Telex', 'Seaway'] as const).map((t) => (
                  <Button key={t} size="sm" variant="secondary" onClick={() => releaseBl(booking.id, t)}>
                    Release {t}
                  </Button>
                ))}
              </>
            )}
            {locked && !editing && (
              <Button size="sm" variant="ghost" onClick={startEdit}>
                Amendment (revision cycle)
              </Button>
            )}
          </div>
        </div>

        <p className="mt-1.5 text-xs text-muted">
          Lifecycle: Draft → Agent/customer edited → Awaiting ops approval → Approved (locked) → Released
          (Original / Telex / Seaway).
        </p>

        {editing && draft ? (
          <div className="mt-4">
            <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
              {BL_FIELD_LABELS.map(({ key, label, source }) => (
                <Field key={key} label={`${label} · ${source}`}>
                  <TextInput
                    value={draft[key]}
                    onChange={(e) => setDraft((d) => (d ? { ...d, [key]: e.target.value } : d))}
                  />
                </Field>
              ))}
            </div>
            <div className="mt-4 flex flex-wrap gap-2">
              <Button
                size="sm"
                onClick={() => {
                  saveBl(booking.id, draft, 'S. Singh', 'ops')
                  setEditing(false)
                }}
              >
                Save — Ops (direct, versioned)
              </Button>
              <Button
                size="sm"
                variant="secondary"
                onClick={() => {
                  saveBl(booking.id, draft, 'Destination agent', 'agent')
                  setEditing(false)
                }}
              >
                Save — Agent (live, versioned)
              </Button>
              <Button
                size="sm"
                variant="secondary"
                onClick={() => {
                  const changes: Partial<BlFields> = {}
                  const baseline = bl?.currentFields
                  for (const { key } of BL_FIELD_LABELS) {
                    if (!baseline || baseline[key] !== draft[key]) changes[key] = draft[key]
                  }
                  submitCustomerBlEdit(booking.id, changes, booking.bookingPartyName)
                  setEditing(false)
                }}
              >
                Submit — Customer (approval-gated)
              </Button>
              <Button size="sm" variant="ghost" onClick={() => setEditing(false)}>
                Cancel
              </Button>
            </div>
          </div>
        ) : bl ? (
          <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">
            {BL_FIELD_LABELS.map(({ key, label }) => (
              <div key={key} className="rounded-btn border border-line bg-surface px-3 py-2">
                <p className="font-mono text-[10px] uppercase tracking-wide text-muted">{label}</p>
                <p className="mt-0.5 text-[13px] text-heading">{bl.currentFields[key] || '—'}</p>
              </div>
            ))}
          </div>
        ) : (
          <p className="mt-4 text-sm text-muted">No BL draft yet — create one after container pickup.</p>
        )}

        {versions.length > 0 && (
          <div className="mt-5 border-t border-line pt-4">
            <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted">
              Version history (bl_versions — append-only)
            </p>
            <div className="space-y-1.5">
              {versions
                .slice()
                .reverse()
                .map((v) => (
                  <div key={v.id} className="flex items-center gap-3 text-xs text-body">
                    <span className="font-mono font-semibold text-heading">v{v.version}</span>
                    <span>{v.editedBy} ({v.editedByRole})</span>
                    <span className="text-muted">{new Date(v.editedAt).toLocaleString()}</span>
                    {v.amendment && (
                      <span className="rounded-badge bg-[#FEF3C7] px-2 py-0.5 text-[10px] font-semibold text-[#B45309]">
                        amendment
                      </span>
                    )}
                  </div>
                ))}
            </div>
          </div>
        )}
      </div>

      {/* ── Documents sequence (doc §5) ── */}
      <div>
        <p className="mb-3 text-xs font-semibold uppercase tracking-wide text-muted">
          Documents — sequence and trigger
        </p>
        <div className="space-y-2">
          {DOC_SEQUENCE.map((d, i) => {
            const uploaded = docs.find((x) => x.docType === d.type)
            return (
              <div
                key={d.type}
                className="flex items-center gap-3 rounded-btn border border-line bg-surface px-4 py-2.5"
              >
                <span className="w-6 font-mono text-[11px] text-muted">{String(i + 1).padStart(2, '0')}</span>
                <div className="flex-1 min-w-0">
                  <p className="text-[13px] font-medium text-heading">{d.type}</p>
                  <p className="truncate text-[11px] text-muted">{d.trigger}</p>
                </div>
                {uploaded ? (
                  <span className="flex items-center gap-1.5 text-xs text-primary">
                    <CheckCircle2 size={14} />
                    {uploaded.status} · {uploaded.uploadedBy}
                  </span>
                ) : (
                  <>
                    <StatusChip status="Pending" />
                    <Button size="sm" variant="ghost" onClick={() => uploadDocument(booking.id, d.type, 'Ops')}>
                      <Upload size={13} /> Upload
                    </Button>
                  </>
                )}
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}
